CC = g++
SRC = ./src
INCLUDE_DIR = ./include
CFLAGS = -std=c++11 -DEUCLID
LIB_DATA = libdata.so

all: main

#Windows
# main: src/knn.cc
# 	$(CC) $(CFLAGS) "C:\Users\dhwan\Documents\Programming\C++ Programming\Machine Learning\MNIST Handwriting\KNN\src\knn.cc" -o main -L"C:\Users\dhwan\Documents\Programming\C++ Programming\Machine Learning\MNIST Handwriting\lib" -I"C:\Users\dhwan\Documents\Programming\C++ Programming\Machine Learning\MNIST Handwriting\KNN\include" -I"C:\Users\dhwan\Documents\Programming\C++ Programming\Machine Learning\MNIST Handwriting\include" -ldata

clean:
	rm main
